// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD_SKMFnPUqa2WLALfsbgUW18P_kSFfIo',
    appId: '1:183868396031:web:2a85959d027f97041997ca',
    messagingSenderId: '183868396031',
    projectId: 'app-angular-6331a',
    authDomain: 'app-angular-6331a.firebaseapp.com',
    databaseURL: 'https://app-angular-6331a-default-rtdb.firebaseio.com',
    storageBucket: 'app-angular-6331a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7bH3UDVn8pC2vmaRmUhHisTYHOfP7i-c',
    appId: '1:183868396031:android:05bb02d7da53493a1997ca',
    messagingSenderId: '183868396031',
    projectId: 'app-angular-6331a',
    databaseURL: 'https://app-angular-6331a-default-rtdb.firebaseio.com',
    storageBucket: 'app-angular-6331a.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAD_SKMFnPUqa2WLALfsbgUW18P_kSFfIo',
    appId: '1:183868396031:web:2a85959d027f97041997ca',
    messagingSenderId: '183868396031',
    projectId: 'app-angular-6331a',
    authDomain: 'app-angular-6331a.firebaseapp.com',
    databaseURL: 'https://app-angular-6331a-default-rtdb.firebaseio.com',
    storageBucket: 'app-angular-6331a.appspot.com',
  );

}